version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:Suiram4oo2!@host.docker.internal:5432/MovieIcon?schema=public
    volumes:
      - backend-data:/app/uploads
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - movie-icon-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - movie-icon-network

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Suiram4oo2!
      - POSTGRES_DB=MovieIcon
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - movie-icon-network

volumes:
  backend-data:
  postgres-data:

networks:
  movie-icon-network:
    driver: bridge 