# This is a monorepo with separate frontend and backend
# We're deploying only the backend to Railway
# See DEPLOYMENT.md for detailed instructions

rootDirectory = "backend"

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate"]

[start]
cmd = "npx prisma migrate deploy && npm start" 